# Base Configuration: Grundeinstellungen für alle Trainings
base_config:
  random_seed: 43
  learning_rate: 0.001
  epoch_num: 100
  training_method: fgd
  dataset_name: mnist
  batch_size: 64
  augment_data: false
  model_type: fc
  optimizer: sgd
  momentum: 0.9
  early_stopping: true
  early_stopping_patience: 5
  early_stopping_delta: 0.01
  dataset_path: _Dataset

# Multi-Parameter Configuration: Parameter für Grid-Search
# Wenn ein Parameter hier definiert ist, wird er für Multi-Training verwendet
# Wenn nicht, wird der Wert aus base_config genommen
multi_params:
  learning_rate:
    - 0.004
    - 0.001
  training_method:
    - fgd

  random_seed:
    - 43

  optimizer:
    - sgd

  # Optional: Weitere Parameter
  # batch_size:
  #   - 32
  #   - 64

  # epoch_num:
  #   - 5
  #   - 10

# Beispiel für verschiedene Setups:
# 1. Nur Learning Rate testen:
#    learning_rate: [0.001, 0.0001]
#    # Alle anderen aus base_config
#
# 2. Vollständiger Grid-Search:
#    learning_rate: [0.01, 0.001, 0.0001]
#    training_method: [bp, fgd]
#    random_seed: [42, 43, 44]
#    batch_size: [32, 64]
#    # = 3 × 2 × 3 × 2 = 36 Kombinationen
