random_seed: 43
learning_rate: 0.1
epoch_num: 2000
training_method: fgd # [bp, fgd]


# Dataset Configurations
#dataset_name: mnist #demo_linear_regression #[demo_linear_regression, mnist, cifar10]
dataset_name: demo_linear_regression
batch_size: 4
augment_data: False

#Early Stopping Configurations
early_stopping: True
early_stopping_patience: 10
early_stopping_delta: 0.001


dataset_path: /home/muskelgurke/PycharmProjects/MA/_Dataset

model_type: demo_linear_regression