random_seed: 42
learning_rate: 0.01
num_epochs: 2


# Dataset Configurations
dataset_name: mnist #lowercase!!!
batch_size: 256
augment_data: False

#Early Stopping Configurations
early_stopping: True
early_stopping_patience: 3


dataset_path: /home/muskelgurke/PycharmProjects/MA/_Dataset