randomSeed: 42
learningRate: 0.01
numEpochs: 1


# Dataset Configurations
dataset: mnist #lowercase!!!
batchSize: 256
augmentData: False

#Early Stopping Configurations
earlyStopping: True
patience: 3


dataset_path: /home/muskelgurke/PycharmProjects/MA/_Dataset