random_seed: 43
learning_rate: 0.001
epoch_num: 10
training_method: fgd # [bp, fgd]


# Dataset Configurations
#dataset_name: mnist # demo_linear_regression #[demo_linear_regression, mnist, cifar10]
dataset_name: mnist
batch_size: 64 #Mnist 64 # Cifar10->128 # for demo_linear_regression 4
augment_data: False
model_type: fc # demo_linear_regression
#Todo: add Optimizer Configurations, learninrate, Momentum, etc.
optimizer:

#Early Stopping Configurations
early_stopping: True
early_stopping_patience: 5
early_stopping_delta: 0.01


dataset_path: /home/muskelgurke/PycharmProjects/MA/_Dataset

