random_seed: 43
learning_rate: 0.1
num_epochs: 2000


# Dataset Configurations
dataset_name: linear_regression #mnist #lowercase!!!
batch_size: 1
augment_data: False

#Early Stopping Configurations
early_stopping: True
early_stopping_patience: 3


dataset_path: /home/muskelgurke/PycharmProjects/MA/_Dataset

model_type: demo_linear_regression