random_seed: 43
learning_rate: 0.1
epoch_num: 1
training_method: fgd # [bp, fgd]


# Dataset Configurations
#dataset_name: mnist # demo_linear_regression #[demo_linear_regression, mnist, cifar10]
#dataset_name: mnist
dataset_name: mnist
batch_size: 64 #2 # for demo_linear_regression 4
augment_data: False
model_type: fc #fc_manual_calculation # demo_linear_regression

#Early Stopping Configurations
early_stopping: True
early_stopping_patience: 5
early_stopping_delta: 0.01


dataset_path: /home/muskelgurke/PycharmProjects/MA/_Dataset

